### ISSUE TITLE
req full packed all modul nginx

### ISSUE THREAD

**Issue by alsyundawy** [ulyaoth/repository#1530] opened 2017-11-06 17:43 UTC
as title can you build full packed all modul nginx like nginx-full on freebsd port

**Comment by sbagmeijer** [comment] 2017-11-06 19:35
Do you mean a Nginx that has all modules compiled into the actual nginx binary instead of having the modules compiled as a separate module?

I tried this once before but the problem is that not all modules can be compiled together, they are not always are compatible.

**Comment by alsyundawy** [comment] 2017-11-06 19:40
how about modular ? all module can be install manual like your pagespeed modul

**Comment by sbagmeijer** [comment] 2017-11-07 11:08
That is how it should be currently:
https://www.ulyaoth.net/repository/nginx.html

If you scroll down you see "plugins" that is what you mean right? all those you can install with yum.
If you would like to see some other modules just let me know and I can add them to the repository.

**Comment by sbagmeijer** [comment] 2017-11-18 19:19
I will close this issue for now, if you miss a module please let us know and we will do our best to add it to the list of instalable modules.

**Closed by sbagmeijer** 2017-11-18 19:19 UTC
